version: '3.3'

services: 
  postgres:
    image: postgres:latest
    environment: 
      - POSTGRES_USER= 
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=

  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  